# 1장. 머신 러닝과 딥런이

## 1.1 인공지능, 머신 러닝과 딥러닝
인공지능(AI)은 인간의 지능을 모방해 사람이 하는 일을 기계가 할 수 있도록 하는 기술
구현 방법: 머신 러닝, 딥러닝
관계: 인공지능 > 머신 러닝 > 딥러닝

머신 러닝 vs 딥러닝
1. 머신 러닝: 주어진 데이터를 인간이 먼저 처리(전처리), 범용적인 목적을 위해 제작된 것으로 데이터의 특징을 스스로 추출하지 못함. 이 과정을 인간이 처리해 주어야 하는 것이 머신 러닝. 즉, 머신 러닝 학습 과정은 각 데이터 특성을 컴퓨터에 인식시키고 학습시켜 문제를 해결
2. 딥러닝: 인간이 하던 작업을 생략. 대량의 데이터를 신경망에 적용하면 컴퓨터가 스스로 분석한 후 답을 찾음.

## 1.2 머신 러닝이란
머신 러닝은 크게 학습 단계, 예측 단계로 구분.
훈련 데이터를 머신 러닝 알고리즘에 적용해 학습시키고, 이 학습 결과로 모형이 생성. 예측 단계에서는 학습 단계에서 생성된 모형에 새로운 데이터를 적용해 결과를 예측

주요 구성 요소: 데이터, 모델(모형)
1. 데이터: 머신 러닝이 학습 모델을 만드는 데 사용하는 것, 실제 데이터 특징이 잘 반영되고 편향되지 않는 훈련 데이터 확보하는 것이 중요
2. 모델: 머신 러닝의 학습 단계에서 얻은 최종 결과물로 가설이라고도 함.
- 모델(가설) 선택
- 모델 학습 및 평가
- 평가를 바탕으로 모델 업데이트

### 1.2.2 머신 러닝 학습 알고리즘
지도 학습, 비지도 학습, 강화 학습
1. 지도 학습: 정답이 무엇인지 컴퓨터에 알려 주고 학습시키는 방법
- 분류, 회귀
2. 비지도 학습: 정답을 알려주지 않고 특징이 비슷한 데이터를 클러스터링(범주화)하여 예측하는 학습 방법
- 군집, 차원 축소
3. 강화 학습: 자신의 행동에 대한 보상을 받으며 학습을 진행

## 1.3 딥러닝이란
- 딥러닝이 머신 러닝과 다른 큰 차이점은 인간의 뇌를 기초로 해 설계했다는 것
- 컴퓨터에 뉴런과 시냅스 개념을 적용
- 복잡하게 연결된 수많은 뉴런을 병렬 연산해 기존에 컴퓨터가 수행하지 못했던 음성/영상 인식 등 처리를 가능하게 함

### 1.3.1 딥러닝 학습 과정
1. 데이터 준비
2. 모델 정의
- 은닉층 개수가 많을수록 성능이 좋아지지만 과적합이 발생할 확률이 높음
3. 모델 컴파일
- 활성화 함수, 옵티마이저, 손실 함수 선택
- 훈련 데이터셋 형태가 연속형(MSE), 이진 분류(Cross Entropy)
4. 모델 훈련
- 전체 훈련 데이터셋에서 일정한 묶음으로 나누어 처리할 수 있는 배치와 훈련의 횟수인 에포크 선택이 중요
5. 모델 예측
- 예측력이 낮다면 파라미터 튜닝 or 신경망 자체를 재설계

### 1.3.2 딥러닝 학습 알고리즘
- 지도 학습, 비지도 학습, 전이 학습

1. 지도 학습: 이미지 분류 - 합성곱 신경망(CNN)
- 이미지 분류는 이미지를 알고리즘에 입력하면 그 이미지가 어떤 클래스에 속하는지 알려주기 때문에 이미지 데이터를 유사한 것끼리 분류할 때 사용
- 이미지 인식은 사진을 분석해 그 안에 있는 사물의 종류를 인식하는 것
- 이미지 분할은 영상에서 사물이나 배경 등 객체 간 영역을 픽셀 단위로 구분하는 기술(X-ray, CT, MRI)
- 시계열 데이터 분류 - 순환 신경망(RNN)

2. 비지도 학습 - 워드 임베딩과 군집
- 워드 임베딩: 단어를 벡터로 표현
- 군집: 아무런 정보가 없는 상태에서 데이터를 분류하는 방법

3. 전이 학습: 사전에 학습이 완료된 모델을 가지고 우리가 원하는 학습에 미세 조정 기법을 이용해 학습시키는 방법

# 2장. 실습 환경 설정과 파이토치 기초
## 2.1 파이토치 개요
파이토치는 딥러닝 프레임워크로 루아 언어로 개발되었떤 토치를 파이썬 버전으로 내놓은 것

대상
- 넘파이를 대체하면서 GPU를 이용한 연산이 필요한 경우
- 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

### 2.1.1 파이토치 특징 및 장점
"GPU에서 텐서 조작 및 동적 신경망 구축이 가능한 프레임워크"
- GPU: 연산 속도를 빠르게 하는 역할
- 텐서: 파치토치의 데이터 형태, 단일 데이터 형식으로 된 자료들의 다차원 행렬, 간단한 명령어 사용해 GPU로 연산 수행
- 동적 신경망: 훈련을 반복할 때마다 네트워크 변경이 가능한 신경망, 예를 들어 학습 중에 은닉층을 추가하거나 제거하는 등 모델의 네트워크 조작이 가능

장점: 단순함, 성능(낮은 CPU 활용), 직관적인 인터페이스

### 2.1.2 파이토치의 아키텍처
파이토치 API - 파이토치 엔진 - 연산 처리
1. 파이토치 API: 사용자가 이해하기 쉬운 API를 제공해 텐서에 대한 처리와 신경망을 구축하고 훈련할 수 있도록 도움
- torch: GPU를 지원하는 텐서 패키지
- torch.autograd: 자동 미분 패키지
- torch.nn: 신경망 구축 및 훈련 패키지
- torch.multiprocessing: 파이썬 멀티프로세싱 패키지
- torch.utils: DataLoader 및 기타 유틸리티 제공하는 패키지

## 2.2 파이토치 기초 문법
### 2.2.1 텐서 다루기
탠서 생성 및 변환

In [ ]:
import torch
print(torch.tensor([[1,2],[3,4]]))
print(torch.tensor([[1,2],[3,4]], device="cuda:0"))
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [ ]:
temp = torch.tensor([[1,2],[3,4]])
print(temp.numpy())

temp = torch.tensor([[1,2],[3,4]], device="cuda:0")
print(temp.to("cpu").numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


텐서의 인덱스 조작
- torch.FloatTensor: 32비트의 부동 소수점
- torch.DoubleTensor: 64비트의 부동 소수점
- torch.LongTensor: 64비트의 부호가 있는 정수

In [ ]:
temp = torch.FloatTensor([1,2,3,4,5,6,7])
print(temp[0], temp[1], temp[-1])
print('------------------')
print(temp[2:5], temp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [ ]:
# 텐서 연산 및 차원 조작
v = torch.tensor([1,2,3])
w = torch.tensor([3,4,6])
print(w-v)

tensor([2, 2, 3])


In [ ]:
# 텐서 차원 조작
temp = torch.tensor([
    [1,2],[3,4]])

print(temp.shape)
print('-------------------')
print(temp.view(4,1))
print('-------------------')
print(temp.view(-1))
print('-------------------')
print(temp.view(1,-1))
print('-------------------')
print(temp.view(-1,1))

torch.Size([2, 2])
-------------------
tensor([[1],
        [2],
        [3],
        [4]])
-------------------
tensor([1, 2, 3, 4])
-------------------
tensor([[1, 2, 3, 4]])
-------------------
tensor([[1],
        [2],
        [3],
        [4]])


### 2.2.2 데이터 준비
- 데이터 호출: 파이썬 라이브러리, 파이토치에서 제공하는 데이터 이용
- 데이터가 이미지일 경우 분산된 파일에서 데이터 읽은 후 전처리 하고 배치 단위로 분할해 처리
- 데이터가 텍스트일 경우 임베딩 과정을 거쳐 서로 다른 길이의 시퀀스를 배치 단위로 분할해 처리

In [ ]:
pip install pandas

In [ ]:
import pandas as pd
import torch
data = pd.read_csv('../class2.csv')

x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
y = torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()

커스텀 데이터셋을 만들어 사용
- 딥러닝은 기본적으로 대량의 데이터를 이용해 모델을 학습시킴
- 데이터를 한 번에 다 부르지 않고 조금씩 나누어 불러서 사용하는 방식이 커스템 데이터셋

In [ ]:
class CustomDataset(torch.utils.data.Dataset):
  def __init__(self):
  def __len__(self):
  def __getitem__(self, index):

In [ ]:
import pandas as pd
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [ ]:
class CustomDataset(Dataset):
  def __init__(self, csv_file):
    self.label = pd.read_csv(csv_file)

  def __init__(self):
    return len(self.label)

  def __getitem__(self, idx):
    sample = torch.tensor(self.label.iloc[idx,0:3]).int()
    label = torch.tensor(self.label.iloc[idx,3]).int()
    return sample, label

tensor_dataset = CustomDataset('../covtype.csv')
dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True)

In [ ]:
for i, data in enumerate(dataset,0):
  print(i, end='')
  batch=data[0]
  print(barch.size())

In [ ]:
# 파이토치에서 제공하는 데이터셋 사용
!pip install requests

In [ ]:
import torchvision.transform as transforms

mnist_transform = transforms.Compose([
    transform.ToTenser(),
    transform.Normalize((0.5,), (1.0,))
])

from torchvision.datasets import MNIST
import requests
download_root = '../chap02/data/MNIST_DATASET'

train_dataset = MNIST(download_root, transform=mnist_transform, train=True,
                      download=True)
valid_dataset = MNIST(download_root, transform=mnist_transform, train=False,
                      download=True)
test_dataset = MNIST(download_root, transform=mnist_transform, train=False,
                      download=True)

### 2.2.3 모델 정의
모듈에 상속한 클래스를 사용
- 계층(layer): 모듈 또는 모듈을 구성하는 한 개의 계층으로 합성곱층, 선형계층 등이 존재
- 모듈(module): 한 개 이상의 계층이 모여 구성된 것, 모듈이 모여 새로운 모듈을 만들 수도 있음.
- 모델(model): 최종적으로 원하는 네트워크, 한 개의 모듈이 모델이 될 수 있음.

In [ ]:
# 단순 신경망 정의
model = nn.Linear(in_features=1, out_features=1, bias=True)

# nn.Module()을 상속해 정의
class MLP(Module):
  def __init__(self, inputs):
    super(MLP, self).__init__()
    self.layer = Linear(inputs, 1)
    self.activation = Sigmoid()

  def forward(self, X):
    X = self.layer(X)
    X = self.activation(X)
    return X

In [4]:
# Sequential 신경망 정의
import torch.nn as nn
class MLP(nn.Module):
  def __init__(self):
    super(MLP, self).__init__()
    self.layer1 = nn.Sequential(
        nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2))

    self.layer2 = nn.Sequential(
        nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2))

    self.layer3 = nn.Sequential(
        nn.Linear(in_features=30*5*5, out_features=10, bias=True),
        nn.ReLU(inplace=True))

    def forward(self, x):
      x = self.layer1(x)
      x = self.layer2(x)
      x = x.view(x.shape[0], -1)
      x = self.layer3(x)
      return x

model = MLP()

print("Printing children\n----------------------")
print(list(model.children()))
print("\n\nPrinting Modules\n-----------------------")
print(list(model.modules()))

Printing children
----------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
-----------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linear(in_features=7

nn.Sequential은 모델 계층이 복잡할수록 효과가 뛰어남.

In [5]:
# 함수로 신경망을 정의
def MLP(in_features=1, hidden_features=20, out_features=1):
  hidden = nn.Linear(n_features=in_features, out_features=hidden_features,
                     bias=True)
  activation = nn.ReLU()
  output = nn.Linear(in_features=hidden_features, out_features=out_features,
                     bias=True)
  net = nn.Sequential(hidden, activation, output)
  return net

### 2.2.4 모델의 파라미터 정의
- 손실 함수(loss funtion): 학습하는 동안 출력과 실제 값 사이의 오차 측정
  - BCELoss: 이진 분류를 위해 사용
  - CrossEntropyLoss: 다중 클래스 분류를 위해 사용
  - MSELoss: 회귀 모델에서 사용
- 옵티마이저(optimizer): 데이터와 손실 함수를 바탕으로 모델의 업데이트 방법 결정
  - step() 메서드 통해 전달받은 파라미터를 업데이트
  - 모델의 파라미터별로 다른 기준을 적용 가능
  - torch.optim.Optimizer(params, defaults)는 모든 옵티마이저의 기본이 되는 클래스
  - zero_grad() 메서드는 옵티마이저에 사용된 파라미터들의 기울기를 0으로 만듦
  - torch.optim.lr_scheduler는 에포크에 따라 학습률을 조절 가능
- 학습률 스케쥴러: 미리 지정한 횟수의 에포크를 지날 때마다 학습률을 감소시켜 줌.
  - optim.lr_scheduler.LambdaLR: 람다 함수를 이용해 그 함수의 결과를 학습률로 설정
  - optim.lr_scheduler.StepLR: 특정 단계마다 학습률을 감마 비율만틈 감소시킴
  - optim.lr_scheduler.MultiStepLR: StepLR과 비슷하지만 특정 단계가 아닌 지정된 에포크에만 감마 비율로 감소시킴
  - optim.lr_scheduler.ExponenitalLR: 에포크마다 이전 학습률에 감마만틈 곱함.
  - optim.lr_scheduler.CosineAnnealingLR: 학습률을 코사인 함수의 형태처럼 변화시킴.
  - optim.lr_scheduler.ReduceLROnPlateau: 학습이 잘되고 있는지 아닌지를 동적으로 학습률을 변화시킬 수 있음.
- 지표: 훈련가 테스트 단계를 모니터링함.

In [ ]:
from torch.optim import optimizer
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer,
                                              lr_lambda=lambda epoch: 0.95 ** epoch)
for epoch in range(1, 100+1):
  for x, y in dataloader:
    optimizer.zero_grad()
loss_fn(model(x), y).backward()
optimizer.step()
scheduler.step()

### 2.2.5 모델 훈련
학습시킨다는 것은 y=wx+b라는 함수에서 w와 b의 적절한 값을 찾는다는 의미

훈련 방법
1. optimizer.zero_grad() 메서드를 이용해 기울기를 초기화
2. loss.backward() 메서드를 이용해 기울기를 자동 계산.

In [ ]:
for epoch in range(100):
  yhat = model(x_train)
  loss = criterion(yhat, y_train)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

### 2.2.6 모델 평가
- 함수와 모듈을 이용하는 두 가지 방법이 있음.

In [6]:
!pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.2/983.2 kB 33.0 MB/s eta 0:00:00


In [ ]:
import torch
import torchmetrics

preds = torch.randn(10,5).softmax(dim=-1)
target = tarch.randint(5, (10,))

acc = torchmetrics.functional.accuracy(preds,target)

metrics = torchmetrics.Accuracy()

n_batches = 10
for i in range(n_batches):
  preds = torch.randn(10,5).softmax(dim=-1)
  target = torch.randint(5,(10,))

  acc = metrics(preds, target)
  print(f"Accuracy on batch {i}: {acc}")

acc = metric.compute()
print(f"Accuracy on all data: {acc}")

### 2.2.7 훈련 과정 모니터링
텐서보드를 이용하면 학습에 사용되는 각종 파라미터 값이 어떻게 변화하는지 손쉽게 시각화 가능
1. 텐서보드를 설정
2. 텐서보드에 기록
3. 텐서보드를 사용해 모델 구조 살펴봄

In [1]:
!pip install tensorboard

In [ ]:
import torch
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter('../chap02/tensorboard')

for epoch in range(num_epochs):
  model.train()
  batch_loss = 0.0

  for i, (x, y) in enumerate(dataloader):
    x, y = x.to(device).float(), y.to(device).float()
    outputs = model(x)
    loss = criterion(outputs, y)
    writer.add_scalar("Loss", loss, epoch)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

writer.close()

In [ ]:
tensorboard --logdir=../chap02/tensorboard --port=6006